[book]
authors = ["Badger"]
language = "en"
multilingual = false
src = "src"
title = "Badger 2-3 Reforged"

[output.html]
default-theme = "dark"
preferred-dark-theme = "navy"
site-url = "/mdbook/"

[build]
build-dir = "public"

[preprocessor.toc]
command = "./mdbook-toc"
renderer = ["html"]